### ISSUE TITLE
Saves

### ISSUE THREAD

**Issue by florensm** [camdenorrb/KPortals#1] opened 2019-10-07 18:21 UTC
If i make a portal it does not save it in the portals.json? 

If i restart it resets the portals

I dont know it like resetted 2 times already so i dont want to do it again so its pretty annoying if you ask me xD

**Comment by camdenorrb** [comment] 2019-10-07 18:23
Thank you for reporting the issue, is there any specific interval for when this happens or anything that triggers it? I’ll take a look at it later today.

**Comment by florensm** [comment] 2019-10-08 16:52
It just happens when i restart, i need to do all the commands again to make it work which can be pretty annoying :>

**Comment by camdenorrb** [comment] 2019-10-09 01:06
I just tested this out on a fresh test server and wasn't able to reproduce this issue. If you don't mind reaching out to me on discord Mr.Midnight#0001 I could look further into the issue.

Other than that, I think this is an issue due to you possibly using a version that isn't listed on the plugin's tested version list. I am closing the issue until we have further information since I wasn't able to reproduce.

**Closed as completed by camdenorrb** 2019-10-09 01:06 UTC

**Comment by camdenorrb** [comment] 2019-10-09 20:52
We have discovered that the issue was due to him stopping the server incorrectly, if you're experiencing this issue, be sure you're not force quiting the server `/stop` is all you need
